Query:
    type: object
    config:
        fields:
            drawByDate:
                type: Draw
                args:
                    date:
                        description: 'Date'
                        type: 'String!'
                resolve: '@=resolver("getDrawByDate", [args["date"]])'

